<?php
     $defaults = array(         'cdn-key'=>'',                          'cdn'=>array('status_txt'=>'FAIL'),                            'top_padding'=>'','print_support'=>'true','rss_style'=>"rss_url",
                                'gplus'=>'',                            'gplus_share_text'=>'Share on google plus',                          'gplus_popup_text'=>'Share this BLOG : TITLE on google plus', 'follow_gplus' => '',
                                'netlog'=>'',                           'netlog_share_text'=>'Share on netlog',                          'netlog_popup_text'=>'Share this BLOG : TITLE on netlog', 'follow_netlog' => '',

                                'nujij'=>'',                            'nujij_share_text'=>'Share on nuJIJ',                          'nujij_popup_text'=>'Share this BLOG : TITLE on nuJIJ',
                                'bookmark'=>'',                         'bookmark_share_text'=>'Bookmark in Browser',                          'bookmark_popup_text'=>'Bookmark this BLOG : TITLE',
                                'sphinn'=>'',                           'sphinn_share_text'=>'Share this on sphinn',                       'sphinn_popup_text'=>'Share this BLOG : TITLE on sphinn',
                                'show_header' => 'true',                'icon_set' => 'default',                  'follow_location'=>'right',             'background_color'=>'878787',
                                'border_color'=>'fff',                  'follow_color'=>'000',                   'extra_print_css'=>'',                  'content' => '',
                                'twitter_text_suffix'=>'',              'width_of_page_minimum'=>'',
                                'extra_css'=>'',                        'excluded_share_pages'=>'',              'list_style'=>'iconOnly',               'size'=>'32',
                                'spacing'=>'3',                         'add_content'=>'true',                   'add_follow'=>'true',                   'add_css'=>'false',
                                'post_rss'=>'yes',                      'facebook' => 'yes',                     'twitter'=>'yes',                       'stumble' => 'yes',
				'digg'=> 'yes',                         'reddit'=> 'yes',                        'hyves' => '',                          'delicious'=>'yes',
                                'print'=>'',                            'orkut'=>'',                             'myspace'=>'',                          
                                'yahoo_buzz'=>'',                       'yahoo_buzz_link'=>'',                                    'youtube'=>'',
                                'linkedin'=>'',                         'dailymotion_link'=>'',                  'soundcloud_link'=>'',                  'foursquare_link'=>'',
                                'vkontakte_link'=>'',                   'plaxo_link'=>'',                        'coconex_link'=>'',                     'gowalla_link'=>'',
                                'xing_link'=>'',                        'twitter_suffix'=>'',                    'vimeo_link'=>'',                       'distance_from_top'=>'100',
                                'follow_list_spacing' =>'10',           'vkontakte'=>'',                                                                 'email'=>'',
                                'tumblr_link'=>'',                      'tumblr'=>'',                            'email_link'=>'',                       'email_body'=>'',
                                'facebook_link' => '',                  'twitter_link'=>'',                      'stumble_link' => '',                   'digg_link'=> '',
                                'reddit_link'=> '',                     'hyves_link' => '',                      'delicious_link'=>'',                   'orkut_link'=>'',
                                'myspace_link'=>'',                     'rss_link'=>'',                          'newsletter_link'=>'',                  'follow_newsletter'=>'',
                                'cssid'=>'1',                           'add_follow_text'=>'true',               'word_value'=>'follow',                 'theme_support'=>'none',
                                'follow_list_style'=>'iconOnly',        'follow_facebook' => '',                 'follow_twitter'=>'',                   'follow_stumble' => '',
				'follow_digg'=> '',                     'follow_reddit'=> '',                    'follow_hyves' => '',                   'follow_delicious'=>'',
                                'follow_orkut'=>'',                     'follow_myspace'=>'',                    'follow_lastfm'=>'',                    'follow_flickr'=>'',
                                'lastfm'=>'',                           'follow_google_buzz'=>'',                'follow_linkedin'=>'',                  'follow_tumblr'=>'',
                                'follow_yelp'=>'',                      'follow_xfire'=>'',                      'follow_yahoo_buzz'=>'',                'follow_vkontakte'=>'',
                                'follow_plaxo'=>'',                     'follow_gowalla'=>'',                    'follow_xing'=>'',                      'twitter_text_default'=>'',
                                'follow_dailymotion'=>'',               'follow_soundcloud'=>'',                 'follow_vimeo'=>'',                     'follow_coconex' => '',
                                'follow_rss'=>'yes',                    'follow_youtube'=>'',                    'tab_size'=>'24',                       'css_images'=>'no',
                                'pinterest'=>'',                        'pinterest_share_text'=>'Pin it on pinterest',                                   'pinterest_popup_text'=>'Pin this BLOG : TITLE on Pinterest',
                                'wp_post'=>'yes',                       'wp_page'=>'yes',                        'wp_home'=>'yes',                       'wp_archive'=>'yes',
                                'wp_author'=>'yes',                     'bit_ly'=>'',                            'bit_ly_code'=>'',                      'follow_foursquare'=>'',
                                'twitter_text'=>'clean',                'add_image_link'=>'true',                'default_email'=>'',                    'word_text'=>__('follow:','share-and-follow'),
                                'default_email_image'=>'',              'author_defaults'=>'authors',            'logo_image_url'=>'',                   'homepage_img'=>'logo',
                                'homepage_image_url'=>'',               'archive_img'=>'logo',                   'archive_image_url'=>'',                'page_image_url'=>'',
                                'post_image_url'=>'',                   'page_img' =>'logo',                     'post_img' =>'gravatar',                'share_text'=>__('share:','share-and-follow'),
                                'share'=>'no',                          'lastfm_link'=>'',                       'flickr_link'=>'',                      'linkedin_link'=>'',
                                'xfire_link'=>'',                       'yelp_link'=>'',                         'background_transparent'=>'no',         'border_transparent'=>'no',
                                'youtube_link'=>'',                     'css_print_excludes'=>'#menu, #navigation, #navi, .menu',
                                'follow_digg'=>'',                      'digg_link'=>'',                          'follow_posterous'=>'',                'follow_ya'=>'',
                                'posterous_link'=>'',                   'ya_link'=>'',                            'css_follow_images'=>'no',
                                'posterous_link_text'=>__('Check my phone feed','share-and-follow'),              'follow_feedburner'=>'',              'feedburner_link'=>'',
                                'technorati'=> '',                           'technorati_share_text'=>__('Share on technorati','share-and-follow'),           'technorati_popup_text'=>__('Share this BLOG : TITLE on technorati','share-and-follow'),
                                'xing'=> '',                           'xing_share_text'=>__('Share on xing','share-and-follow'),           'xing_popup_text'=>__('Share this BLOG : TITLE on xing','share-and-follow'),
                                'ya_link_text'=>__('Connect with me','share-and-follow'),
                                'follow_slideshare'=>'',                'slideshare_link_text'=>__('See my presentations','share-and-follow'), 'slideshare_link'=>'',

                                'follow_wordpress'=>'',           'wordpress_link_text'=>__('Me on wordpress','share-and-follow'), 'wordpress_link'=>'',
                                'follow_technet'=>'',             'technet_link_text'=>__('My technical items','share-and-follow'), 'technet_link'=>'',
                                'follow_squidoo'=>'',             'squidoo_link_text'=>__('Check me on Squidoo','share-and-follow'), 'squidoo_link'=>'',
                                'follow_plurk'=>'',               'plurk_link_text'=>__('Connect with me on Plurk','share-and-follow'), 'plurk_link'=>'',
                                'follow_meetup'=>'',              'meetup_link_text'=>__('Come to the Meeting','share-and-follow'), 'meetup_link'=>'',
                                'follow_getglue'=>'',             'getglue_link_text'=>__('Wanna see my stickers?','share-and-follow'), 'getglue_link'=>'',
                                'follow_ning'=>'',                'ning_link_text'=>__('Wanna see my stickers?','share-and-follow'), 'ning_link'=>'',
                                'follow_behance'=>'', 'behance_link_text'=>__('Look at me on Behance','share-and-follow'), 'behance_link'=>'',

                                'follow_hi5'=>'', 'hi5_link_text'=>__('Become friends with me on hi5','share-and-follow'), 'hi5_link'=>''
                              , 'follow_gplus'=>'' , 'gplus_link_text'=>__('Be in my Circle','share-and-follow'), 'gplus_link'=>'',
                                
                                'follow_formspring'=>'', 'formspring_link_text'=>__('Follow me on Formspring','share-and-follow'), 'formspring_link'=>'',
                                'follow_fwisp'=>'',  'fwisp_link_text'=>__('Follow my finances on fwisp','share-and-follow'), 'fwisp_link'=>'',

                                'follow_iwiw'=>'', 'iwiw_link_text'=>__('Follow me on iwiw','share-and-follow'), 'iwiw_link'=>'',
                                'follow_netlog'=>'', 'netlog_link_text'=>__('Follow me on netlog','share-and-follow'), 'netlog_link'=>'',
                                'follow_panoramio'=>'',  'panoramio_link_text'=>__('Follow me on Panoramio','share-and-follow'), 'panoramio_link'=>'',
                                'follow_pinterest'=>'',  'pinterest_link_text'=>__('Pin me on Pinterest','share-and-follow'), 'pinterest_link'=>'',
                                'follow_statusnet'=>'',  'statusnet_link_text'=>__('Keep up with me on statusnet','share-and-follow'), 'statusnet_link'=>'',
                                'follow_tuenti'=>'', 'tuenti_link_text'=>__('Follow me on Tuenti','share-and-follow'), 'tuenti_link'=>'',


                                'follow_bebo'=>'',                'bebo_link_text'=>__('Find me on Bebo','share-and-follow'), 'bebo_link'=>'',
                                'follow_faves'=>'',               'faves_link_text'=>__('See my Faves','share-and-follow'), 'faves_link'=>'',
                                'follow_identica'=>'',            'identica_link_text'=>__('Connect with me on identi.ca','share-and-follow'), 'identica_link'=>'',
                                'follow_bandcamp'=>'','follow_deviantart'=>'','follow_imdb'=>'', 'follow_itunes'=>'','follow_moddb'=>'','follow_picasa'=>'','follow_sphinn'=>'',
                                'bandcamp_link'=>'','deviantart_link'=>'','imdb_link'=>'', 'itunes_link'=>'','moddb_link'=>'','picasa_link'=>'','sphinn_link'=>'',


                                'bebo'=> '',               'bebo_share_text'=>__('Share on bebo','share-and-follow'),          'bebo_popup_text'=>__('Share this BLOG : TITLE on bebo','share-and-follow'),
                                'identica'=> '',           'identica_share_text'=>__('Share on identica','share-and-follow'),  'identica_popup_text'=>__('Share this BLOG : TITLE on identica','share-and-follow'),
                                'dzone'=> '',              'dzone_share_text'=>__('Share on dzone','share-and-follow'),        'dzone_popup_text'=>__('Share this BLOG : TITLE on dzone','share-and-follow'),
                                'fark'=> '',               'fark_share_text'=>__('Share on fark','share-and-follow'),          'fark_popup_text'=>__('Share this BLOG : TITLE on fark','share-and-follow'),
                                'faves'=> '',              'faves_share_text'=>__('Share on faves','share-and-follow'),        'faves_popup_text'=>__('Share this BLOG : TITLE on faves','share-and-follow'),
                                'linkagogo'=> '',          'linkagogo_share_text'=>__('Share on linkagogo','share-and-follow'),'linkagogo_popup_text'=>__('Share this BLOG : TITLE on linkagogo','share-and-follow'),
                                'mrwong'=> '',             'mrwong_share_text'=>__('Share on mrwong','share-and-follow'),      'mrwong_popup_text'=>__('Share this BLOG : TITLE on mrwong','share-and-follow'),
                                'netvibes'=> '',           'netvibes_share_text'=>__('Share on netvibes','share-and-follow'),  'netvibes_popup_text'=>__('Share this BLOG : TITLE on netvibes','share-and-follow'),
                                'friendfeed'=> '',         'friendfeed_share_text'=>__('Share on FriendFeed','share-and-follow'),  'friendfeed_popup_text'=>__('Share this BLOG : TITLE on FriendFeed','share-and-follow'),
                                'friendfeed_ning'=>'',     'friendfeed_link_text'=>__('Check my feeds','share-and-follow'), 'friendfeed_link'=>'','follow_friendfeed'=>'',

                                'wpsc_top_of_products_page'=>'no','wpsc_product_before_description'=>'no', 'wpsc_product_addon_after_descr'=>'no',

                                'follow_email'=>'', 'email_link_text'=>__('Sign up for emails','share-and-follow'), 'email_link'=>'',
                                'excluded_follow_pages'=>'','follow_page'=>'yes','follow_post'=>'yes','follow_archive'=>'yes','follow_home'=>'yes','follow_author'=>'yes',
                                'vkontakte_share_text'=>__('Share on vkontakte','share-and-follow'),
                                // 'mixx_share_text' =>__('Mixx it up','share-and-follow'),
                                'linkedin_share_text' =>__('Share on Linkedin','share-and-follow'),
                                'facebook_share_text' =>__('Recommend on Facebook','share-and-follow'),
                                'twitter_share_text' =>__('Tweet about it','share-and-follow'),
                                'tumblr_share_text' =>__('Tumblr it','share-and-follow'),
                                'stumble_share_text' =>__('Share with Stumblers','share-and-follow'),
                                'digg_share_text' =>__('Digg this post','share-and-follow'),
                                'reddit_share_text' =>__('share via Reddit','share-and-follow'),
                                'hyves_share_text' =>__('Tip on Hyves','share-and-follow'),
                                'delicious_share_text' =>__('Bookmark on Delicious','share-and-follow'),
                                'orkut_share_text' =>__('Share on Orkut','share-and-follow'),
                                'myspace_share_text' =>__('Share via MySpace','share-and-follow'),
                                'facebook_link_text' => __('Become my Facebook friend','share-and-follow'),
                                'twitter_link_text'=>__('Tweet with me','share-and-follow'),
                                'tumblr_link_text'=>__('Read my Tumbles.','share-and-follow'),
                                'xfire_link_text'=>__('Come on a mission','share-and-follow'),
                                'stumble_link_text' => __('Follow my Stumbles','share-and-follow'),
                                'hyves_link_text' => __('Become my friend on Hyves','share-and-follow'),
                                'orkut_link_text'=>__('Become Orkut Buddies','share-and-follow'),
                                'myspace_link_text'=>__('Become a myspace follower','share-and-follow'),
                                'foursquare_link_text'=>__('Follow me on FourSquare','share-and-follow'),
                                'soundcloud_link_text'=>__('Listen to my music','share-and-follow'),
                                'feedburner_link_text'=>__('Stay updated','share-and-follow'),

                                'coconex_link_text'=>__('Connect with us','share-and-follow'),
                                'plaxo_link_text'=>__('Join my address book','share-and-follow'),
                                'vkontakte_link_text'=>__('Become Friends','share-and-follow'),
                                'gowalla_link_text'=>__('Follow my actions','share-and-follow'),
                                'xing_link_text'=>__('Connect with us','share-and-follow'),

                                'sphinn_link_text'=>__('Read my posts','share-and-follow'),
                                'itunes_link_text'=>__('Listen to me','share-and-follow'),
                                'deviantart_link_text'=>__('See my artwork','share-and-follow'),
                                'moddb_link_text'=>__('Gamer? my mods','share-and-follow'),
                                'picasa_link_text'=>__('See my pictures','share-and-follow'),
                                'bandcamp_link_text'=>__('Listen to the band','share-and-follow'),
                                'imdb_link_text'=>__('Read my reviews','share-and-follow'),
                                'delicious_link_text'=>__('See what I share','share-and-follow'),
                                'digg_link_text'=>__('Digg my stuff','share-and-follow'),

                                'vimeo_link_text'=>__('Watch my videos','share-and-follow'),
                                'dailymotion_link_text'=>__('Tune to my channel','share-and-follow'),
                                'yahoo_buzz_share_text'=>__('Buzz it up','share-and-follow'),
                                // 'google_buzz_share_text'=>__('Buzz it up','share-and-follow'),
                                'google_buzz_link'=>__('Buzz it up','share-and-follow'),
                                'yahoo_buzz_link_text'=>__('Follow me','share-and-follow'),
                                'lastfm_link_text'=>__('Check my tunes','share-and-follow'),
                                'google_buzz_link_text'=>__('Join my conversations','share-and-follow'),
                                'linkedin_link_text'=>__('Connect with me','share-and-follow'),
                                'yelp_link_text'=>__('Read reviews','share-and-follow'),
                                'flickr_link_text'=>__('See my photos','share-and-follow'),
                                'newsletter_link_text'=>__('Join the newsletter','share-and-follow'),
                                'rss_link_text'=>__('RSS','share-and-follow'),
                                'email_share_text'=>__('Tell a friend','share-and-follow'),
                                'email_body_text'=>__('here is a link to a site I really like. ','share-and-follow'),
                                'youtube_link_text'=>__('Subscribe to my YouTube Channel','share-and-follow'),
                                'post_rss_share_text'=>__('Subscribe to the comments on this post','share-and-follow'),
                                'print_share_text'=>__('Print for later','share-and-follow'),
                                // 'mixx_popup_text' => __('Share this BLOG : TITLE on Mixx','share-and-follow'),
                                'linkedin_popup_text' => __('Share this BLOG : TITLE on Linkedin','share-and-follow'),
                                'facebook_popup_text' => __('Recommend this BLOG : TITLE on Facebook','share-and-follow'),
                                'stumble_popup_text'=> __('Share this BLOG : TITLE with Stumblers','share-and-follow'),
                                'twitter_popup_text'=>__('Tweet this BLOG : TITLE on Twitter','share-and-follow'),
                                'tumblr_popup_text'=>__('Tumblr. this BLOG : TITLE ','share-and-follow'),
                                'delicious_popup_text'=>__('Bookmark this BLOG : TITLE on Delicious','share-and-follow'),
                                'vkontakte_popup_text'=>__('Share this BLOG : TITLE on vkontakte','share-and-follow'),
                                'digg_popup_text'=>__('Digg this BLOG : TITLE','share-and-follow'),
                                'reddit_popup_text'=>__('Share this BLOG : TITLE on Reddit','share-and-follow'),
                                'hyves_popup_text'=>__('Tip this BLOG : TITLE on Hyves','share-and-follow'),
                                'orkut_popup_text'=>__('Share this BLOG : TITLE on Orkut','share-and-follow'),
                                'myspace_popup_text'=>__('Share this BLOG : TITLE via MySpace','share-and-follow'),
                                'post_rss_popup_text'=>__('Follow this BLOG : TITLE comments','share-and-follow'),
                                'print_popup_text'=>__('Print this BLOG : TITLE for reading later','share-and-follow'),
                                'email_popup_text'=>__('Tell a friend about this BLOG : TITLE ','share-and-follow'),
                                // 'google_buzz_popup_text'=>__('Buzz up this BLOG : TITLE ','share-and-follow'),
                                'yahoo_buzz_popup_text'=>__('Buzz up this BLOG : TITLE ','share-and-follow'),

                                'blogger_popup_text'=>__('Share this BLOG : TITLE on Blogger','share-and-follow'),  'blogger'=>'',  'follow_blogger'=>'',   'blogger_share_text'=>'Blog this!',  'blogger_link' => '', 'blogger_link_text' => 'Follow me on Blogger',

                                'like_topleft'=>'no','like_topright'=>'no','like_bottom'=>'no','like_style'=>'box_count','like_width'=>__('50','share-and-follow'),'like_faces'=>'false','like_verb'=>'like',
                                'like_color'=>'light','like_font'=>'arial','bit_ly_domain'=>'','tweet_topleft'=>'no','tweet_topright'=>'no','tweet_bottom'=>'no','tweet_width'=>'55','tweet_style'=>'vertical',
                                'tweet_wpsc_top_of_products_page'=>'', 'tweet_wpsc_product_before_description'=>'', 'tweet_wpsc_product_addon_after_descr'=>'',
                                'like_wpsc_top_of_products_page'=>'', 'like_wpsc_product_before_description'=>'', 'like_wpsc_product_addon_after_descr'=>'',
                                'posterous'=>'','posterous_share_text'=>__('Share on Posterous','share-and-follow'),          'posterous_popup_text'=>__('Share this BLOG : TITLE on Posterous','share-and-follow'),
                                'tweet_via'=>'',
                                'stumble_style'=>'5','stumble_topleft'=>'','stumble_topright'=>'','stumble_bottom'=>'','stumble_wpsc_top_of_products_page'=>'', 'stumble_wpsc_product_before_description'=>'', 'stumble_wpsc_product_addon_after_descr'=>'',
         
                               'googleplus_lang'=>'en-US', 'googleplus_style'=>'inline','googleplus_size'=>'tall','googleplus_topleft'=>'','googleplus_topright'=>'','googleplus_bottom'=>'','googleplus_wpsc_top_of_products_page'=>'', 'googleplus_wpsc_product_before_description'=>'', 'googleplus_wpsc_product_addon_after_descr'=>'',
                               'pinterest_style'=>'vertical','pinterest_topleft'=>'','pinterest_topright'=>'','pinterest_bottom'=>'','pinterest_wpsc_top_of_products_page'=>'', 'pinterest_wpsc_product_before_description'=>'', 'pinterest_wpsc_product_addon_after_descr'=>'',
                               'pinterest_images'=>'no','pins_to_add'=>'all',



                    );

